### PR TITLE
Added link to osticket-fetch-note plugin

### PR DESCRIPTION
**Pull request by bkonetzny**

### CODE REVIEW

**Comment by clonemeagain** [comment]
Hey,

The reason that's failing is because the repo is already linked, it's under `Development Resources`.

Fetch Note Plugin - Demonstrates ticket hooks and configs, makes a CURL request and adds a Note to a ticket thread.

Wasn't sure it was for most users.

**Comment by bkonetzny** [comment]
Ah, sorry, you are absolutely right - didn't expect it down the list at the development section.
I don't really see this as an development example, I think it serves a real world use and is not documented enough to be listed in the development section.

Would it be okay for you if we move this plugin up to the "Community Plugins" an remove it from "Development Resources" section? If thats ok for you, I would update the PR accordingly.
I don't want to argue here, if you insist we can keep it in the development section too - it's fine for me for as long as its on the list at all :)

**Comment by clonemeagain** [comment]
That's OK mate. ☺️

Happy to merge that.

**Comment by bkonetzny** [comment]
Cool, updated the PR :)

**Comment by clonemeagain** [comment]
Sweet, cheers mate.

**Pull request merged**
